### PR TITLE
add new type: question

### LINKED ISSUE #2: add admonition type: question
I think it would be super useful if a new admonition type would be added: `question` to highlight a quesiton.

### PR DESCRIPTION
**Pull request by arcturus140**
This PR adds a new type of Admonition: Question. It closes #2. 

image

Issues:

1. Black background on black text. With nested admonitions the text is unreadable after 10th level. I need to change colours

### CODE REVIEW

**Comment by arcturus140** [comment]
final result:

image

**Comment by bgub** [comment]
@arcturus140 this looks great! My one concern is that the colors don't seem to match perhaps quite as well with the others. Maybe you could use a color scheme generator tool?

**Comment by bgub** [comment]
@arcturus140 here's a cool resource: https://coolors.co/3498db-2ecc71-e67e22-e74c3c-004777

**Comment by bgub** [comment]
Perhaps a saffron, other yellow, or dark blue or green would work well.

**Comment by arcturus140** [comment]
This should do it:

image

otherwise please pick colours yourself and I apply them.

**Comment by bgub** [comment]
@arcturus140 this looks great! I'll try to merge and publish when I get home.

Thanks for your work!

**Review by arcturus140 — COMMENTED** [review]
lgtm

**Comment by arcturus140** [comment]
@nebrelbug how is the review going? Do you think it can be merged?

**Comment by bgub** [comment]
@arcturus140 sorry this took so long! Just merged :)

**Comment by bgub** [comment]
@arcturus140 [react-admonitions 2.1.0](https://www.npmjs.com/package/react-admonitions) is now published :clap:! Thanks for being so patient while waiting for me to merge!

One last random question: where did you get the SVG for the emoji icon?

[Edit]: never mind, I found it in Octicons. It doesn't show up in the main page so I was really curious how you got it :smile:

**Pull request merged**
